version: '3.4'

networks:
  monitoring:
    external: true

# logging section
#x-logging: 
#  &loki-logging
#  driver: loki
#  options:
#    loki-url: http://host.docker.internal:3100/loki/api/v1/push

services:
  users-ui:
    build:
      context: ./src/main/ui/dist
      dockerfile: ../Dockerfile
    image: kjtully/users-ui:latest
    container_name: users-ui
    labels:
      description: "Angular Java - Angular Users UI"
    ports:
      - "4200:4200"
    networks:
      - monitoring
      - default
    #logging: *loki-logging

  users-api:
    build: ./docker
    image: kjtully/users-api:20.10
    container_name: users-api
    labels:
      desciption: "Angular Java - Java Users API"
    environment:
      SERVER_PORT: "8082"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "$APPDYNAMICS_AGENT_APPLICATION_NAME"
      APPDYNAMICS_AGENT_TIER_NAME: "users-api"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "users-api-container"
      # MacOS - uncomment the NETVIZ env vars to use local docker-compose network
      #APPDYNAMICS_NETVIZ_AGENT_HOST: "$APPDYNAMICS_NETVIZ_AGENT_HOST"
      #APPDYNAMICS_NETVIZ_AGENT_PORT: "$APPDYNAMICS_NETVIZ_AGENT_PORT"
      APPDYNAMICS_BROWSER_EUM_APPKEY: "$APPDYNAMICS_BROWSER_EUM_APPKEY"
      APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP"
      APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS"
      APPDYNAMICS_BROWSER_EUM_BEACON_HTTP: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTP"
      APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS"
      # Docker Hostname to pre-populate Jaeger link in UI
      DOCKER_HOSTNAME: "$DOCKER_HOSTNAME"
    ports:
      - "8082:8082"
    networks:
      - monitoring
      - default
    #logging: *loki-logging
    deploy:
      resources:
        limits:
          cpus: '2'
          #NanoCpus: '750000000'
          memory: 512M
        reservations:
          cpus: '1'
          #NanoCPUs: '250000000'
          memory: 256M

