version: '3.6'

#networks:
  #internal-net:
    #name: workbench_subnet
services:
  db:
    image: postgres:10.5
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
        #proxy:
        #image: nginx:latest
        #container_name: proxy
        #ports:
        #- "4200:80"
        #volumes:
        #- ./frontend/dist:/usr/share/nginx/html
        #- ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        #environment:
        #- NGINX_HOST=ninrod.org
        #- NGINX_PORT=80
        #networks:
        #- internal-net
